### ISSUE TITLE
Network structure

### ISSUE THREAD

**Issue by liujiyuan13** [huybery/MvDSCN#3]
Hello, 

I am very interested to your idea that employing both diversity and universality nets to find the robust latent expressions.

In the paper, some datasets with extracted features, such as Yale, are adopted. I am wondering their network structures but do not find in the paper and code. Could you please tell me more about them ?
Thank you so much !

Jiyuan Liu
liujiyuan13@nudt.edu.cn

**Comment by huybery** [comment]
Hi @liujiyuan13 , I have send multi-feature code for your mail, please note to check. 
If you have no other questions, please close the issue after recevie code.

**Comment by liujiyuan13** [comment]
Thanks so much !
