### ISSUE TITLE
How to train BBCSPort Datasets?

### ISSUE THREAD

**Issue by dugzzuli** [huybery/MvDSCN#4]
each sample for BBCSport dataset is one-dimensional. How to train bbcsport dataset? Do you use one-dimensional convolution for training?

**Comment by huybery** [comment]
We first reshape feature map from 1-D to 2-D, and then perform the 2-D convolution operation for it.
We've tried 1-D convolution and FC, but the performance is not good.

**Comment by dugzzuli** [comment]
Thank you very much.

**Comment by dugzzuli** [comment]
Has this paper been published?

**Comment by huybery** [comment]
Unfortunately, it remains under review. 😿
