### ISSUE TITLE
about the number of channels in the convolutional layer

### ISSUE THREAD

**Issue by xxLinLucky** [huybery/MvDSCN#5]
Hello, this is a question about the number of channels in the convolutional layer

The paper described:
We use three-layer encoders with [64, 32, 16] channels, and threelayer decoders with [16, 32, 64] channels correspondingly.

But the code is:
    def encoder1(self, x):
        net = self.conv_block(x,   64)
        net = self.conv_block(net, 64)
        net = self.conv_block(net, 64)
        return net

Did I misunderstand? Thank you

**Comment by huybery** [comment]
This belongs to the hyper-parameter of the network, which can be adjusted according to different data, not a fixed value.
